- name: configuring catalogue component
  hosts: mongodb
  become: yes
  tasks:
  - name: setting up NPM source
     # Here -sL stands shell we are runnning shell,So we using ansible.builtin.shell
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  - name: Install Nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
      
  - name: checking if user is already created
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: yes

  - name: printing the exiting status
    ansible.builtin.debug:
      msg: "{{output.rc}}"

  - when: output.rc!=0 
    name: creating the roboshop user
    ansible.builtin.user:
      name: roboshop

    


